### ISSUE TITLE
Problems with the apple script in the workflow

### ISSUE THREAD

**Issue by ChangXord** [mikelxc/sidecar-alfredworkflow#1]
I am using Chinese for my system, which causes the apple script to throw an error message saying that there are no available iPads. Also, the AirPlay icon must be displayed in the menu bar, which is another problem. Can u help fix these problems? Many thanks!

**Comment by jaredmichaelwilliams** [comment]
@ChangXord  Open the alfred workflow settings, go to the "Sidecar" workflow. Double click the one that says "/usr/bin/osascript" on top 

Change this line
`			click (menu item 1 of menu 1 of result whose title contains "iPad")`
to this line
`			click (menu item 1 of menu 1 of result whose Title contains "iPad")`

I also opened a PR so its fixed going forward

https://github.com/mikelxc/sidecar-alfredworkflow/pull/3

**Comment by ChangXord** [comment]
thx!
