### ISSUE TITLE
Doesn't seem to work with Big Sur. I'm using a 2018 Mac Mini

### ISSUE THREAD

**Issue by jasonminsookim** [mikelxc/sidecar-alfredworkflow#2]

**Comment by jaredmichaelwilliams** [comment]
@jasonminsookim Open the alfred workflow settings, go to the "Sidecar" workflow. Double click the one that says "/usr/bin/osascript" on top 

Change this line
`			click (menu item 1 of menu 1 of result whose title contains "iPad")`
to this line
`			click (menu item 1 of menu 1 of result whose Title contains "iPad")`

I also opened a PR so its fixed going forward

https://github.com/mikelxc/sidecar-alfredworkflow/pull/3

**Comment by mikelxc** [comment]
Merged to master
